apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: your-dockerhub-username/jenkinscicd:latest
        ports:
        - containerPort: 9540
        envFrom:
        - configMapRef:
            name: app-config