apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinscicd-deployment
  labels:
    app: jenkinscicd
spec:
  replicas: 2 # Initial number of replicas
  selector:
    matchLabels:
      app: jenkinscicd
  template:
    metadata:
      labels:
        app: jenkinscicd
    spec:
      containers:
      - name: jenkinscicd
        image: golamrabbani3587/jenkinscicd:v1
        ports:
        - containerPort: 9540
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: NODE_ENV
          value: "production"
