apiVersion: v1
kind: Service
metadata:
  name: jenkinscicd-service
  labels:
    app: jenkinscicd
spec:
  type: ClusterIP
  selector:
    app: jenkinscicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9540
